### ISSUE TITLE
Crashing on android

### ISSUE THREAD

**Issue by Venryx** [MiincGu/react-native-file-manager#4]
Crashes on Android whenever I select a file, or even press the back button to cancel.

Note that the Javascript handler is completely empty, so it's not due to my doing something strange post-selection.

Error stack trace:
```
11-20 06:05:31.027: D/AndroidRuntime(12249): Shutting down VM
11-20 06:05:31.029: E/AndroidRuntime(12249): FATAL EXCEPTION: main
11-20 06:05:31.029: E/AndroidRuntime(12249): Process: com.lucidlink, PID: 12249
11-20 06:05:31.029: E/AndroidRuntime(12249): java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:260)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:627)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:135)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread.access$1300(ActivityThread.java:151)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.os.Looper.loop(Looper.java:135)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at java.lang.reflect.Method.invoke(Native Method)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
11-20 06:05:31.029: E/AndroidRuntime(12249): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
11-20 06:05:33.508: I/Process(12249): Sending signal. PID: 12249 SIG: 9
```

**Comment by Venryx** [comment]
Sorry. Posted to the wrong repo. 😐

(Meant to post here: https://github.com/Lichwa/react-native-file-picker/issues/3)
